name: mapiah
description: Graphical interface for Therion cave mapping software written in Flutter.
version: 0.2.24
homepage: https://mapiah.org
repository: https://github.com/rsevero/mapiah.git
issue_tracker: https://github.com/rsevero/mapiah/issues

environment:
  sdk: "^3.9.0"

# Add regular dependencies here.
dependencies:
  analyzer: ^8.2.0
  charset: ^2.0.0
  collection: ^1.19.0
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.0
  intl: any
  intl_utils: ^2.8.7
  logger: ^2.5.0
  markdown_widget: ^2.3.2+8
  meta: ^1.0.0
  mobx: ^2.0.0
  open_file: ^3.0.0
  package_info_plus: ^9.0.0
  path: ^1.9.0
  path_drawing: ^1.0.1
  path_provider: ^2.0.0
  petitparser: ^7.0.1
  toml: ^0.17.0
  url_launcher: ^6.3.1
  web: ^1.1.1
  window_size: ^0.1.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.0
  path_provider_platform_interface: ^2.1.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/help/en/keyboard_shortcuts_edit.md
    - assets/help/en/keyboard_shortcuts_main.md
    - assets/help/en/mapiah_home_help.md
    - assets/help/en/th2_file_edit_page_help.md
    - assets/help/images/buttonAddArea.png
    - assets/help/images/buttonAddElement.png
    - assets/help/images/buttonAddLine.png
    - assets/help/images/buttonAddPoint.png
    - assets/help/images/buttonDelete.png
    - assets/help/images/buttonImages.png
    - assets/help/images/buttonLineEdit.png
    - assets/help/images/buttonRedo.png
    - assets/help/images/buttonScraps.png
    - assets/help/images/buttonSelectElement.png
    - assets/help/images/buttonSnap.png
    - assets/help/images/buttonUndo.png
    - assets/help/images/buttonZoomFile.png
    - assets/help/images/buttonZoomIn.png
    - assets/help/images/buttonZoomOneToOne.png
    - assets/help/images/buttonZoomOptions.png
    - assets/help/images/buttonZoomOut.png
    - assets/help/images/buttonZoomScrap.png
    - assets/help/images/buttonZoomSelection.png
    - assets/help/images/iconAbout.png
    - assets/help/images/iconAbout.png
    - assets/help/images/iconBack.png
    - assets/help/images/iconClose.png
    - assets/help/images/iconHelp.png
    - assets/help/images/iconLanguage.png
    - assets/help/images/iconOpenFile.png
    - assets/help/images/iconSave.png
    - assets/help/images/iconSaveAs.png
    - assets/help/pt/keyboard_shortcuts_edit.md
    - assets/help/pt/keyboard_shortcuts_main.md
    - assets/icons/add_element-addArea.png
    - assets/icons/add_element-addElement.png
    - assets/icons/add_element-addLine.png
    - assets/icons/add_element-addPoint.png
    - assets/icons/change-image-tool.png
    - assets/icons/change-scrap-tool.png
    - assets/icons/org.mapiah.mapiah.png
    - assets/icons/select-tool.png
    - assets/icons/snap-tool.png
    - assets/icons/zoom_minus.png
    - assets/icons/zoom_one_to_one.png
    - assets/icons/zoom_plus_minus.png
    - assets/icons/zoom_plus.png
    - assets/icons/zoom_selection.png
    - assets/icons/zoom-out-scrap.png
    - assets/images/image_not_found.png
